name: Branch Protection Rule - Edited
on:
  branch_protection_rule:
    types:
      - edited
jobs:
  print-context:
    concurrency: branch_protection_rule_edited-${{ github.ref }}
    uses: ./.github/workflows/wc-print-context.yml
