name: Discussion - Unpinned
on:
  discussion:
    types:
      - unpinned
jobs:
  print-context:
    concurrency: discussion_unpinned-${{ github.ref }}
    uses: ./.github/workflows/wc-print-contexts.yml
