name: Discussion - Answered
on:
  discussion:
    types:
      - answered
jobs:
  print-context:
    concurrency: discussion_answered-${{ github.ref }}
    uses: ./.github/workflows/wc-print-contexts.yml
