name: Issues - Demilestoned
on:
  issues:
    types:
      - demilestoned
jobs:
  print-context:
    concurrency: issues_demilestoned-${{ github.ref }}
    uses: ./.github/workflows/wc-print-contexts.yml
