name: Pull Request Workflow
on:
  pull_request:

env:
  SAMPLE_WORKFLOW_VARIABLE: sample

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    env:
      SAMPLE_JOB_VARIABLE: sample
    steps:
    - id: github-context
      name: Print GitHub Context
      run: |
        echo '${{ toJSON( github ) }}'
    - id: env-context
      name: Print Env Context
      env:
        SAMPLE_STEP_VARIABLE: sample
      run: |
        echo '${{ toJSON( env ) }}'
    - id: vars-context
      name: Print Vars Context
      run: |
        echo '${{ toJSON( vars ) }}'
    - id: job-context
      name: Print Job Context
      run: |
        echo '${{ toJSON( job ) }}'
    - id: steps-context
      name: Print Steps Context
      run: |
        echo '${{ toJSON( steps ) }}'
    - id: runner-context
      name: Print Runner Context
      run: |
        echo '${{ toJSON( runner ) }}'
