name: Pull Request Target - Locked
on:
  pull_request_target:
    types:
      - locked
jobs:
  print-context:
    concurrency: pull_request_target_locked-${{ github.ref }}
    uses: ./.github/workflows/wc-print-context.yml
