name: Pull Request Review Comment - Edited
on:
  pull_request_review_comment:
    types:
      - edited
jobs:
  print-context:
    concurrency: pull_request_review_comment_edited-${{ github.ref }}
    uses: ./.github/workflows/wc-print-contexts.yml
