name: Pull Request Target - Reopened
on:
  pull_request_target:
    types:
      - reopened
jobs:
  print-context:
    concurrency: pull_request_target_reopened-${{ github.ref }}
    uses: ./.github/workflows/wc-print-contexts.yml
