name: Pull Request - Auto Merge Enabled
on:
  pull_request:
    types:
      - auto_merge_enabled
jobs:
  print-context:
    concurrency: pull_request_auto_merge_enabled-${{ github.ref }}
    uses: ./.github/workflows/wc-print-contexts.yml
