name: Pull Request Target - Unlabeled
on:
  pull_request_target:
    types:
      - unlabeled
jobs:
  print-context:
    concurrency: pull_request_target_unlabeled-${{ github.ref }}
    uses: ./.github/workflows/wc-print-context.yml
