name: Release - Prereleased
on:
  release:
    types:
      - prereleased
jobs:
  print-context:
    concurrency: release_prereleased-${{ github.ref }}
    uses: ./.github/workflows/wc-print-contexts.yml
