name: Workflow Artifact
on:
  workflow_dispatch
jobs:
  update-artifact:
    name: Update Artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get Previous Artifact
      id: get-previous-artifact
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh run download -n my-artifact
      continue-on-error: true
    - name: Create Artifact
      id: create-artifact
      run: |
        date | tee ./my-artifact.txt
    - name: Upload Updated Artifact
      id: upload-updated-artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./my-artifact.txt
      

