name: Workflow Run - Completed
on:
  workflow_run:
    types:
      - completed
    workflows:
      - Push
jobs:
  print-context:
    concurrency: workflow_run_completed-${{ github.ref }}
    uses: ./.github/workflows/wc-print-contexts.yml
